services:
  lprs:
    image: laurfb/lprs_demo:latest
    restart: always
    ports:
      - "1935:1935"
      - "1936:1936"
      - "1985:1985"
      - "6828:6828/udp"
      - "8223:8223"
      - "8228:8228/udp"
      - "9303:9303"
      - "9998:9998"
      - "10080:10080/udp"
    environment:
      DEMO_MODE: "production_ready"
      LOG_LEVEL: "info"
      API_KEY: "YiR5XwMsLPheegFqRSyBSChXU"


